[app]
host = "localhost"
port = 8088

[database]
database_type = "postgres"
host = "localhost"
name = "ams"
user = "postgres"
password = "password"
port = 5432

[oss]
access_key_id = ""
access_key_secret = ""
region = ""
end_point = ""
bucket = ""