[app]
host = "localhost"
port = 80

[database]
database_type = "mysql"
host = "localhost"
name = "ams"
user = "ams"
password = "ams_client"
port = 3306

[oss]
access_key_id = ""
access_key_secret = ""
region = ""
end_point = ""
bucket = ""