[app]
host = "localhost"
port = 80

[database]
host = "localhost"
name = "postgres"
user = "postgres"
password = "renzhichao"
port = 5432

[oss]
access_key_id = ""
access_key_secret = ""
region = ""
end_point = ""
bucket = ""